trying to reformat stuff

diff --git a/.github/workflows/preview-deploy.yml b/.github/workflows/preview-deploy.yml
--- a/.github/workflows/preview-deploy.yml
+++ b/.github/workflows/preview-deploy.yml
@@ -11,6 +11,77 @@ env:
   FLY_ORG: personal
 
 jobs:
+  defaults:
+    environment: staging
+  setup_env:
+    runs-on: ubuntu-latest
+    name: Set up workflow environment
+    steps:
+      - name: Generate deploy slugs
+        id: generate_slugs
+        env:
+          pr_number: ${{ github.event.number }}
+          branch: ${{ github.head_ref }}
+          commit: ${{ github.sha }}
+        run: |
+          clean_branch=${branch//\//-}
+          short_commit=${commit:0:8}
+
+          echo "clean_branch=${clean_branch}" >> $GITHUB_OUTPUT
+          echo "short_commit=${short_commit}" >> $GITHUB_OUTPUT
+          echo "slug=${pr_number}-${clean_branch}-${short_commit}" >> $GITHUB_OUTPUT
+        outputs:
+          clean_branch: ${{ steps.generate_slugs.outputs.clean_branch}}
+          short_commit: ${{ steps.generate_slugs.outputs.short_commit}}
+          slug: ${{ steps.generate_slugs.outputs.slug}
+
+  deploy_meilisearch:
+    runs-on: ubuntu-latest
+    name: Deploy Meilisearch
+    needs: [setup_env]
+    
+    env:
+      $app_name: ${{ needs.setup_env.outputs.slug }}-meilisearch
+      $master_key: ${{ needs.setup_env.output.slug }}-staging-meili-key
+    
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          sparse-checkout: |
+            search
+      - uses: superfly/flyctl-actions/setup-flyctl@master
+      - name: Launch app
+        working-directory: search
+        run: |
+          flyctl launch \
+              --name $app_name \
+              --no-deploy \
+              --build-only \
+              --copy-config \
+              --now \
+              --no-deploy \
+              --remote-only \
+              --region $FLY_REGION \
+              --org $FLY_ORG \
+              ;
+      - name: Deploy app
+        working-directory: search
+        run: |
+          flyctl deploy \
+            --app $app_name \
+            --config fly.toml \
+            --remote-only \
+            --strategy immediate \
+            --region $FLY_REGION \
+            --env MEILI_MASTER_KEY=${master_key} \
+            --env MEILI_HTTP_ADDR=localhost:7700 \
+            ;
+
+    
+      
+
+
+jobs:
   # TODO: would https://github.com/dorny/paths-filter#conditional-execution
   # cause desync/unknown variables?
   env_setup:
@@ -30,169 +101,169 @@ jobs:
       clean_branch: ${{ steps.preview_slug.outputs.CLEAN_BRANCH }}
       slug: ${{ steps.preview_slug.outputs.PREVIEW_SLUG }}
 
-  preview_deploy:
-    runs-on: ubuntu-latest
+  # preview_deploy:
+  #   runs-on: ubuntu-latest
 
-    needs: [env_setup]
+  #   needs: [env_setup]
 
-    # env-name template: preview-${{ github.event.number }}
-    concurrency:
-      group: preview-${{ github.event.number }}
+  #   # env-name template: preview-${{ github.event.number }}
+  #   concurrency:
+  #     group: preview-${{ github.event.number }}
 
-    environment:
-      name: preview-${{ github.event.number }}
-      url: ${{ steps.deploy.outputs.url }}
+  #   environment:
+  #     name: preview-${{ github.event.number }}
+  #     url: ${{ steps.deploy.outputs.url }}
 
-    env:
-      prefix: ${{ needs.env_setup.outputs.slug }}
-      meili_key: ${{ needs.env_setup.outputs.slug}}-staging-meili-key
-      db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging
+  #   env:
+  #     prefix: ${{ needs.env_setup.outputs.slug }}
+  #     meili_key: ${{ needs.env_setup.outputs.slug}}-staging-meili-key
+  #     db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging
 
-    steps:
-      - uses: actions/checkout@v3
-      - uses: superfly/flyctl-actions/setup-flyctl@master
-      - name: Deploy Meilisearch
-        run: |
-          cd search
-          flyctl launch \
-            --name ${prefix}-meilisearch \
-            --no-deploy \
-            --build-only \
-            --copy-config \
-            --now \
-            --no-deploy \
-            --remote-only \
-            --region $FLY_REGION \
-            --org $FLY_ORG \
-            ;
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: superfly/flyctl-actions/setup-flyctl@master
+  #     - name: Deploy Meilisearch
+  #       run: |
+  #         cd search
+  #         flyctl launch \
+  #           --name ${prefix}-meilisearch \
+  #           --no-deploy \
+  #           --build-only \
+  #           --copy-config \
+  #           --now \
+  #           --no-deploy \
+  #           --remote-only \
+  #           --region $FLY_REGION \
+  #           --org $FLY_ORG \
+  #           ;
             
-          flyctl deploy \
-            --app ${prefix}-meilisearch \
-            --config fly.toml \
-            --remote-only \
-            --strategy immediate \
-            --region $FLY_REGION \
-            --env MEILI_MASTER_KEY=${meili_key} \
-            --env MEILI_HTTP_ADDR=localhost:7700 \
-            ;
+  #         flyctl deploy \
+  #           --app ${prefix}-meilisearch \
+  #           --config fly.toml \
+  #           --remote-only \
+  #           --strategy immediate \
+  #           --region $FLY_REGION \
+  #           --env MEILI_MASTER_KEY=${meili_key} \
+  #           --env MEILI_HTTP_ADDR=localhost:7700 \
+  #           ;
             
-          cd ..
+  #         cd ..
 
-      - name: Provision Postgres cluster
-        run: |
-          if ! flyctl status --app $db_name &> /dev/null; then
-          flyctl postgres create \
-            --name $db_name \
-            --fork-from community-maps-db \
-            --vm-size shared-cpu-1x \
-            --volume-size 1 \
-            --initial-cluster-size 1 \
-            --region $FLY_REGION \
-            --org $FLY_ORG \
-            | awk '1;/Postgres cluster/{exit}'
-          fi
+  #     - name: Provision Postgres cluster
+  #       run: |
+  #         if ! flyctl status --app $db_name &> /dev/null; then
+  #         flyctl postgres create \
+  #           --name $db_name \
+  #           --fork-from community-maps-db \
+  #           --vm-size shared-cpu-1x \
+  #           --volume-size 1 \
+  #           --initial-cluster-size 1 \
+  #           --region $FLY_REGION \
+  #           --org $FLY_ORG \
+  #           | awk '1;/Postgres cluster/{exit}'
+  #         fi
 
-      - name: Deploy Django
-        env:
-          appname: ${{ env.prefix }}-django
-        run: |
-          cd backend
+  #     - name: Deploy Django
+  #       env:
+  #         appname: ${{ env.prefix }}-django
+  #       run: |
+  #         cd backend
 
-          echo "::group::Launch and build app"
-          flyctl launch \
-            --name $appname \
-            --no-deploy \
-            --build-only \
-            --copy-config \
-            --now \
-            --no-deploy \
-            --remote-only \
-            --region $FLY_REGION \
-            --org $FLY_ORG \
-            ;
-          echo "::endgroup::"
+  #         echo "::group::Launch and build app"
+  #         flyctl launch \
+  #           --name $appname \
+  #           --no-deploy \
+  #           --build-only \
+  #           --copy-config \
+  #           --now \
+  #           --no-deploy \
+  #           --remote-only \
+  #           --region $FLY_REGION \
+  #           --org $FLY_ORG \
+  #           ;
+  #         echo "::endgroup::"
 
-          echo "::group::Attach to postgres"
-          flyctl postgres attach \
-            $db_name \
-            --app $appname \
-            --database-user "user_${appname//-/_}" \
-            --database-name "community_maps_django" \
-            --verbose \
-            --yes \
-            ;
-          echo "::endgroup::"
+  #         echo "::group::Attach to postgres"
+  #         flyctl postgres attach \
+  #           $db_name \
+  #           --app $appname \
+  #           --database-user "user_${appname//-/_}" \
+  #           --database-name "community_maps_django" \
+  #           --verbose \
+  #           --yes \
+  #           ;
+  #         echo "::endgroup::"
 
-          echo "::group::Deploy and release"
-          flyctl deploy \
-            --app $appname \
-            --config fly.toml \
-            --remote-only \
-            --strategy immediate \
-            --region $FLY_REGION \
-            --env DJANGO_SETTINGS_MODULE=api.settings.staging \
-            --env ALLOWED_HOSTS=${appname}.fly.dev \
-            --env CSRF_TRUSTED_ORIGINS=https://${appname}.fly.dev \
-            --env MEILISEARCH_HOST=https://${prefix}-meilisearch.fly.dev \
-            --env MEILISEARCH_KEY=${meili_key} \
-            ;
-          echo "::endgroup::"
+  #         echo "::group::Deploy and release"
+  #         flyctl deploy \
+  #           --app $appname \
+  #           --config fly.toml \
+  #           --remote-only \
+  #           --strategy immediate \
+  #           --region $FLY_REGION \
+  #           --env DJANGO_SETTINGS_MODULE=api.settings.staging \
+  #           --env ALLOWED_HOSTS=${appname}.fly.dev \
+  #           --env CSRF_TRUSTED_ORIGINS=https://${appname}.fly.dev \
+  #           --env MEILISEARCH_HOST=https://${prefix}-meilisearch.fly.dev \
+  #           --env MEILISEARCH_KEY=${meili_key} \
+  #           ;
+  #         echo "::endgroup::"
 
-          cd ..
+  #         cd ..
 
-      - name: Deploy Next
-        env:
-          appname: ${{ env.prefix }}
-          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
-          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
-        run: |
-          cd frontend
+  #     - name: Deploy Next
+  #       env:
+  #         appname: ${{ env.prefix }}
+  #         CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
+  #         CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
+  #       run: |
+  #         cd frontend
           
-          api_host=https://${prefix}-django.fly.dev
-          meili_host=https://${prefix}-meilisearch.fly.dev
-          host=https://${prefix}.fly.dev
+  #         api_host=https://${prefix}-django.fly.dev
+  #         meili_host=https://${prefix}-meilisearch.fly.dev
+  #         host=https://${prefix}.fly.dev
 
-          flyctl launch \
-            --name $appname \
-            --copy-config \
-            --now \
-            --remote-only \
-            --strategy immediate \
-            --region $FLY_REGION \
-            --org $FLY_ORG \
-            --build-arg API_HOST=$api_host \
-            --build-arg CLOUDINARY_CLOUD_NAME=drk1rc6ld \
-            --build-arg CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
-            --build-arg CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
-            --env NEXT_PUBLIC_MEILISEARCH_HOST=$meili_host \
-            --env NEXT_PUBLIC_HOST=$host \
-            --env NEXT_PUBLIC_MAPBOX_TOKEN=pk.eyJ1Ijoic3Jocm1hcHMiLCJhIjoiY2xpcXJ1bmpzMGEwcDNmcGk3ZjdpNDMydyJ9.WCTvtUC2zCBs-xz0p8QOeg \
-            ;
+  #         flyctl launch \
+  #           --name $appname \
+  #           --copy-config \
+  #           --now \
+  #           --remote-only \
+  #           --strategy immediate \
+  #           --region $FLY_REGION \
+  #           --org $FLY_ORG \
+  #           --build-arg API_HOST=$api_host \
+  #           --build-arg CLOUDINARY_CLOUD_NAME=drk1rc6ld \
+  #           --build-arg CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
+  #           --build-arg CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
+  #           --env NEXT_PUBLIC_MEILISEARCH_HOST=$meili_host \
+  #           --env NEXT_PUBLIC_HOST=$host \
+  #           --env NEXT_PUBLIC_MAPBOX_TOKEN=pk.eyJ1Ijoic3Jocm1hcHMiLCJhIjoiY2xpcXJ1bmpzMGEwcDNmcGk3ZjdpNDMydyJ9.WCTvtUC2zCBs-xz0p8QOeg \
+  #           ;
         
-          cd ..
+  #         cd ..
 
-  teardown_on_failure:
-    if: ${{ failure() }}
-    needs: [env_setup, preview_deploy]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: superfly/flyctl-actions/setup-flyctl@master
-      - env:
-          prefix: ${{ needs.env_setup.outputs.slug }}
-          db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging
-        run: |
-          flyctl apps destroy -y $prefix-meilisearch || true
-          flyctl apps destroy -y $db_name || true
-          flyctl apps destroy -y $prefix-django || true
-          flyctl apps destroy -y $prefix || true
+  # teardown_on_failure:
+  #   if: ${{ failure() }}
+  #   needs: [env_setup, preview_deploy]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: superfly/flyctl-actions/setup-flyctl@master
+  #     - env:
+  #         prefix: ${{ needs.env_setup.outputs.slug }}
+  #         db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging
+  #       run: |
+  #         flyctl apps destroy -y $prefix-meilisearch || true
+  #         flyctl apps destroy -y $db_name || true
+  #         flyctl apps destroy -y $prefix-django || true
+  #         flyctl apps destroy -y $prefix || true
 
-  # Clean up environment on PR close
-  cleanup_environment:
-    if: ${{ always() && github.event.action == 'closed' }}
-    needs: [env_setup, preview_deploy]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: strumwolf/delete-deployment-environment@v2.3.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          environment: preview-${{ github.event.number }}
+  # # Clean up environment on PR close
+  # cleanup_environment:
+  #   if: ${{ always() && github.event.action == 'closed' }}
+  #   needs: [env_setup, preview_deploy]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: strumwolf/delete-deployment-environment@v2.3.0
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         environment: preview-${{ github.event.number }}
